In [1]:
import geopandas as gpd
import matplotlib.pyplot as plt

In [8]:
gdf = gpd.read_file('../output/2021/Munich_GHGco_v2_3_year2021.gpkg')

In [9]:
gdf

,id,ISO3,Year,GNFR_Sector,SourceType,Identifier,CO2,NOX,CO,CH4,PM,CO2_bio,geometry
0,97.0,DEU,2021,D,A,None,1.116205e+02,0.000000,0.000000,0.728119,NaN,NaN,"POLYGON ((675503.47 5336499.375, 675500.627 53..."
1,97.0,DEU,2021,HR_outdoor,A,None,4.794204e+01,NaN,NaN,NaN,NaN,47.942039,"POLYGON ((675503.47 5336499.375, 675500.627 53..."
2,97.0,DEU,2021,F_hot,A,None,0.000000e+00,0.000000,0.000000,0.000000,0.0,0.000000,"POLYGON ((675503.47 5336499.375, 675500.627 53..."
3,97.0,DEU,2021,K,A,None,0.000000e+00,0.000000,0.000000,546.161562,NaN,NaN,"POLYGON ((675503.47 5336499.375, 675500.627 53..."
4,97.0,DEU,2021,J,A,None,0.000000e+00,0.036967,0.720756,0.003186,NaN,NaN,"POLYGON ((675503.47 5336499.375, 675500.627 53..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
297100,NaN,DEU,2021,A,P,hkw_freimann,2.194000e+08,42800.000000,14970.000000,NaN,NaN,NaN,POINT Z (692938 5340569 100)
297101,NaN,DEU,2021,A,P,hw_koppstrasse,1.090000e+07,6100.000000,290.000000,NaN,NaN,NaN,POINT Z (688772 5330025 50)
297102,NaN,DEU,2021,A,P,hw_perlach,3.570000e+07,13800.000000,260.000000,NaN,NaN,NaN,POINT Z (697990 5331015 54)
297103,NaN,DEU,2021,A,P,hw_riem,3.100000e+06,900.000000,60.000000,NaN,NaN,NaN,POINT Z (702006 5334844 17.5)
297104,NaN,DEU,2021,A,P,hw_freiham,1.430000e+07,4800.000000,190.000000,NaN,NaN,NaN,POINT Z (679015 5334660 30)

In [10]:
A = gpd.read_file('../data/GNFR A/2024/2024_GNFR_A.gpkg')

In [11]:
A

,name,CO2,CO,NOx,geometry
0,hkw_nord_block_1,350000000.0,15233.280211,220469.033357,POINT Z (696219 5339810 130)
1,hkw_nord_block_2,826700000.0,23812.436268,316861.834428,POINT Z (696285 5339740 130)
2,hkw_nord_block_3,270000000.0,30991.645478,177875.045405,POINT Z (696124 5339762 130)
3,hkw_nord_hw,1900000.0,13.571429,515.714286,POINT Z (696219 5339810 130)
4,hkw_sued_GuD_1,1400000.0,38.888889,1135.555556,POINT Z (690226 5332186 130)
5,hkw_sued_GuD_2,507400000.0,14615.253614,194478.885677,POINT Z (690196 5332024 90)
6,hw_theresienstrasse,11200000.0,373.333333,3792.280702,POINT Z (691601 5336005 60)
7,hw_gaisbergstrasse,6500000.0,162.754304,2339.593114,POINT Z (694218 5334626 60)
8,hkw_kathi_kobus_strasse,400000.0,4.000000,200.000000,POINT Z (690064 5337189 50)
9,hkw_freimann,119400000.0,970.870185,27797.546362,POINT Z (692938 5340569 100)
10,hw_koppstrasse,5900000.0,338.216561,2559.171975,POINT Z (688772 5330025 50)
11,hw_perlach,9700000.0,95.802469,3814.135802,POINT Z (697990 5331015 54)
12,hw_riem,4600000.0,234.394904,2065.605096,POINT Z (702006 5334844 17.5)
13,hw_freiham,3300000.0,0.000000,1034.248788,POINT Z (679015 5334660 30)

In [12]:
len(gdf[gdf['GNFR_Sector']=='A'])

14