# Convert files to netcdf format
Convert yearly emission inventory to *.netcdf format.<br>
Conversion is based on original script from Lionel Constantin from EMPA.<br>

In [39]:
import os
import geopandas as gpd
import numpy as np
import pandas as pd
import xarray as xr
import matplotlib.pyplot as plt

from emiproc.inventories import Inventory
from emiproc.grids import RegularGrid
from emiproc.regrid import remap_inventory
from emiproc.plots import plot_inventory
from emiproc.exports.rasters import export_raster_netcdf
from emiproc.exports.netcdf import nc_cf_attributes
from emiproc.utilities import Units
from emiproc.inventories.utils import drop

plt.style.use("default")

### Load inventory and related files

In [40]:
# load inventory gpkg
YEAR = 2024

root = os.path.dirname(os.path.abspath(''))
path = os.path.join(root, 'output', str(YEAR), f'Munich_GHGco_v2_3_year{YEAR}.gpkg')
gdf = gpd.read_file(path)

#gdf.geometry = gdf.geometry.centroid # convert polygons to points

gdf.head()

,id,ISO3,Year,GNFR_Sector,SourceType,Identifier,CO2,NOX,CO,CH4,PM,CO2_bio,geometry
0,97.0,DEU,2024,D,A,None,111.620497,0.000000,0.000000,0.728119,NaN,NaN,"POLYGON ((675503.47 5336499.375, 675500.627 53..."
1,97.0,DEU,2024,HR_outdoor,A,None,47.942039,NaN,NaN,NaN,NaN,47.942039,"POLYGON ((675503.47 5336499.375, 675500.627 53..."
2,97.0,DEU,2024,F_hot,A,None,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,"POLYGON ((675503.47 5336499.375, 675500.627 53..."
3,97.0,DEU,2024,K,A,None,0.000000,0.000000,0.000000,546.161562,NaN,NaN,"POLYGON ((675503.47 5336499.375, 675500.627 53..."
4,97.0,DEU,2024,J,A,None,0.000000,0.036967,0.720756,0.003186,NaN,NaN,"POLYGON ((675503.47 5336499.375, 675500.627 53..."

In [41]:
gdf[gdf['GNFR_Sector'] == 'A']

,id,ISO3,Year,GNFR_Sector,SourceType,Identifier,CO2,NOX,CO,CH4,PM,CO2_bio,geometry
297091,NaN,DEU,2024,A,P,hkw_nord_block_1,350000000.0,220469.033357,15233.280211,NaN,NaN,NaN,POINT Z (696219 5339810 130)
297092,NaN,DEU,2024,A,P,hkw_nord_block_2,826700000.0,316861.834428,23812.436268,NaN,NaN,NaN,POINT Z (696285 5339740 130)
297093,NaN,DEU,2024,A,P,hkw_nord_block_3,270000000.0,177875.045405,30991.645478,NaN,NaN,NaN,POINT Z (696124 5339762 130)
297094,NaN,DEU,2024,A,P,hkw_nord_hw,1900000.0,515.714286,13.571429,NaN,NaN,NaN,POINT Z (696219 5339810 130)
297095,NaN,DEU,2024,A,P,hkw_sued_GuD_1,1400000.0,1135.555556,38.888889,NaN,NaN,NaN,POINT Z (690226 5332186 130)
297096,NaN,DEU,2024,A,P,hkw_sued_GuD_2,507400000.0,194478.885677,14615.253614,NaN,NaN,NaN,POINT Z (690196 5332024 90)
297097,NaN,DEU,2024,A,P,hw_theresienstrasse,11200000.0,3792.280702,373.333333,NaN,NaN,NaN,POINT Z (691601 5336005 60)
297098,NaN,DEU,2024,A,P,hw_gaisbergstrasse,6500000.0,2339.593114,162.754304,NaN,NaN,NaN,POINT Z (694218 5334626 60)
297099,NaN,DEU,2024,A,P,hkw_kathi_kobus_strasse,400000.0,200.000000,4.000000,NaN,NaN,NaN,POINT Z (690064 5337189 50)
297100,NaN,DEU,2024,A,P,hkw_freimann,119400000.0,27797.546362,970.870185,NaN,NaN,NaN,POINT Z (692938 5340569 100)
297101,NaN,DEU,2024,A,P,hw_koppstrasse,5900000.0,2559.171975,338.216561,NaN,NaN,NaN,POINT Z (688772 5330025 50)
297102,NaN,DEU,2024,A,P,hw_perlach,9700000.0,3814.135802,95.802469,NaN,NaN,NaN,POINT Z (697990 5331015 54)
297103,NaN,DEU,2024,A,P,hw_riem,4600000.0,2065.605096,234.394904,NaN,NaN,NaN,POINT Z (702006 5334844 17.5)
297104,NaN,DEU,2024,A,P,hw_freiham,3300000.0,1034.248788,0.000000,NaN,NaN,NaN,POINT Z (679015 5334660 30)

In [42]:
# Instantiate emiproc inventory
substances = ['CO2', 'NOX', 'CO', 'CH4', 'PM', 'CO2_bio']
sectors = gdf['GNFR_Sector'].unique()

inv = Inventory.from_gdf(gdfs={
    category: gdf.loc[gdf['GNFR_Sector'] == category, substances + ['geometry']] for category in sectors
},
    name='Munich',
)

# create regular grid based on TNO grid bounds
TNO_grid = gpd.read_file(os.path.join(root, 'data', 'TNO_100m_grid_munich.gpkg'))
x_min, y_min, x_max, y_max = TNO_grid.total_bounds

grid_tno = RegularGrid(
    xmin=x_min, ymin=y_min, xmax=x_max, ymax=y_max, dx=1/600, dy=1/1200)

grid_footprint = RegularGrid(
    xmin=np.floor(x_min*100)/100, ymin=np.floor(y_min*100)/100,
    xmax=np.ceil(x_max*100)/100, ymax=np.ceil(y_max*100)/100+0.01, dx=0.01, dy=0.01)

# remap inventor to regular Grid
inv_mapped_100m = remap_inventory(inv, grid_tno)
inv_mapped_1km = remap_inventory(inv, grid_footprint)

inv_mapped_100m.year = YEAR
inv_mapped_100m.name = "Munich GHG & co-emitted species inventory"

inv_mapped_1km.year = YEAR
inv_mapped_1km.name = "Munich GHG & co-emitted species inventory"

In [43]:
filepath = export_raster_netcdf(
    inv=inv_mapped_1km,
    path=os.path.join(root, 'output', str(YEAR), f'Munich_GHGco_v2_3_year{YEAR}_FP_1km_grid.nc'),
    group_categories=True,
    unit=Units.KG_PER_YEAR,
    var_name_format="{substance}",
    lon_name="lon",
    lat_name="lat",
    netcdf_attributes=nc_cf_attributes(
        references="https://github.com/tum-esm/tum-mci",
        institution="Technical University Munich (TUM)",
        author="Daniel Kühbacher, TUM",
        contact="daniel.kuehbacher@tum.de",
        title=f"Munich City Emissions Inventory {YEAR}",
        source="Bottom-Up calculations based on local data for GNFR A, C, F and Human Respiration. National downscaled for all other sectors (TNO-GHGco v4.1)",
        comment=("The data was generated by a team from the Technical University Munich (TUM) and TNO."),
        additional_attributes={
            "TUM_Authors": [
                "Kühbacher, Daniel <daniel.kuehbacher@tum.de>",
                "Aigner, Patrick <patrick.aigner@tum.de>",
                "Chen, Jia <jia.chen@tum.de>",
                "Hinderer, Julian <julian.hinderer@tum.de>",
                "Suhendra, Michael <michael.suhendra@tum.de>",
                "Yirtar, Beyza <beyza.yirtar@tum.de>"
            ],
            "TNO_Authors": [
                "Super, Ingrid, <ingrid.super@tno.nl>",
                "Denier van der Gon, Hugo <hugo.deniervandergon@tno.nl>",
                "Dröge, Rianne <rianne.droge@tno.nl>",
                "Schoenecker, Emma <emma.schoenmakers@tno.nl>",
                "Hohenberger, Tilman <tilman.hohenberger@tno.nl>"
            ]
        }
    ),
)

In [44]:
filepath = export_raster_netcdf(
    inv=inv_mapped_100m,
    path=os.path.join(root, 'output', str(YEAR), f'Munich_GHGco_v2_3_year{YEAR}_TNO_100m_grid.nc'),
    group_categories=True,
    unit=Units.KG_PER_YEAR,
    var_name_format="{substance}",
    lon_name="lon",
    lat_name="lat",
    netcdf_attributes=nc_cf_attributes(
        references="https://github.com/tum-esm/tum-mci",
        institution="Technical University Munich (TUM)",
        author="Daniel Kühbacher, TUM",
        contact="daniel.kuehbacher@tum.de",
        title=f"Munich City Emissions Inventory {YEAR}",
        source="Bottom-Up calculations based on local data for GNFR A, C, F and Human Respiration. National downscaled for all other sectors (TNO-GHGco v4.1)",
        comment=("The data was generated by a team from the Technical University Munich (TUM) and TNO."),
        additional_attributes={
            "TUM_Authors": [
                "Kühbacher, Daniel <daniel.kuehbacher@tum.de>",
                "Aigner, Patrick <patrick.aigner@tum.de>",
                "Chen, Jia <jia.chen@tum.de>",
                "Hinderer, Julian <julian.hinderer@tum.de>",
                "Suhendra, Michael <michael.suhendra@tum.de>",
                "Yirtar, Beyza <beyza.yirtar@tum.de>"
            ],
            "TNO_Authors": [
                "Super, Ingrid, <ingrid.super@tno.nl>",
                "Denier van der Gon, Hugo <hugo.deniervandergon@tno.nl>",
                "Dröge, Rianne <rianne.droge@tno.nl>",
                "Schoenecker, Emma <emma.schoenmakers@tno.nl>",
                "Hohenberger, Tilman <tilman.hohenberger@tno.nl>"
            ]
        }
    ),
)

In [45]:
ds = xr.open_dataset(os.path.join(root, 'output', str(YEAR), f'Munich_GHGco_v2_3_year{YEAR}_FP_1km_grid.nc'))